version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dev.dockerfile
      target: dev
    command: yarn dev
    ports:
      - 8080:8080
      - 8088:8088
    volumes:
      - .:/usr/src/gqltsapi
      - /usr/src/gqltsapi/.build
      - /usr/src/gqltsapi/node_modules
