version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dev.dockerfile
      target: "${APP_ENV:?APP_ENV}"
    command: yarn "${APP_ENV:?APP_ENV}"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPASS: pgpass
      PGUSER: pguser
      PGDATABASE: "gqltsapi_${APP_ENV:?APP_ENV}"
    ports:
      - 8080:8080
      - 8088:8088
    volumes:
      - .:/usr/src/gqltsapi
      - /usr/src/gqltsapi/.build
      - /usr/src/gqltsapi/node_modules
  db:
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: "gqltsapi_${APP_ENV:?APP_ENV}"
    image: postgres:11.2-alpine
